<div class="col-xs-12 header">
	<div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 name">健康助手查询中心</div>
</div>
<div class="col-xs-12 login">
	<form method="POST" action="/account/login">
		<div class="form_item"><label>手机号</label><input type="text" name="mobile"/></div>
		<div class="form_item"><label>密码</label><input type="password" name="pwd"/></div>
		<div class="form_item"><input type="submit" class="submit" value="登陆" /> <input type="reset" class="reset" value="重置" /></div>
	</form>
</div>