
<html lang="en">
  	<head>
  		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <title>Ibird智能手表</title>
	    <link rel="stylesheet" href="gulp/bower_components/bootstrap/dist/css/bootstrap.css" />
	    <link rel="stylesheet" href="gulp/bower_components/font-awesome/css/font-awesome.css" />
	    <link rel="stylesheet" href="css/ehr.css">
      <link rel="stylesheet" href="css/common.css?v=2">
      <link rel="stylesheet" href="css/login.css">
  	</head>
    <script type="text/javascript">
      var config = {url: 'http://www.sayyllg.com'};
    </script>
    <body>
            <?php echo $this->content; ?>
    </body>
</html>
